### ISSUE TITLE
Adaptar diseño para que se visualice correctamente en pantallas ultrawide

### ISSUE THREAD

**Issue by rsciriano** [CAEAragon/caearagon.org#16]
Este CSS lo podría arreglar

```css

.home {
       background-position: top;
}

.site {
    max-width: 1920px;
}

```
